app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => ['web']], function () {
Route::resource('tasks', 'TasksController');
Route::get('/', [
    'as' => 'home',
    'uses' => 'PagesController@home'
]);
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
	Route::resource('rosters', 'RostersController');
    //
});

app/Level.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Level extends Model
{
    //
}

app/Roster.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;



class Roster extends Model

{


    public function sport()
{
    return $this->belongsTo('App\Sport', 'sport_id');
}

public function year()
{
    return $this->belongsTo('App\Year', 'year_id');
}

public function level()
{
    return $this->belongsTo('App\Level', 'level_id');
}

	protected $fillable = [
        'sport_id',
        'level_id',
        'year_id',
        'first_name',
        'last_name',
        'jersey',
        'position',
        'height_feet',
        'height_inches',
        'weight',
        'hometown',
        'years_at_sfc',
        'verse',
        'food',
        'photo'
];


}

app/Sport.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sport extends Model
{


    public function roster()
    {
        return $this->hasMany('Roster', 'sport_id');
    }


}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Year.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Year extends Model
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class PagesController extends Controller
{

	public function home()
{
    return view('pages.home');
}
    //
}

app/Http/Controllers/RostersController.php
<?php

namespace App\Http\Controllers;
use Session;
use App\Roster;
use App\Sport;
use App\Level;
use App\Year;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class RostersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
            $rosters = Roster::all();
                    $sports = Sport::lists('name', 'id');
        $levels = Level::lists('name', 'id');
        $years = Year::lists('name', 'id');

           return view('rosters.index',compact('sports','levels','years'))->withRosters($rosters);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sports = Sport::lists('name', 'id');
        $levels = Level::lists('name', 'id');
        $years = Year::lists('name', 'id');

        return View('rosters.create', compact('sports','levels','years'));
        
  
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            $input = $request->all();

    Roster::create($input);

    return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)

    {       
         


            $rosters = roster::find($id);
            
            $sports= $rosters->sport;

    return view('rosters.show')->withRosters($rosters);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/home.blade.php
@extends('layouts.master')

@section('content')



<h1>Welcome Home</h1>
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores, possimus, ullam? Deleniti dicta eaque facere, facilis in inventore mollitia officiis porro totam voluptatibus! Adipisci autem cumque enim explicabo, iusto sequi.</p>
<hr>

<h1>Orders</h1>

<table class="table table-striped"> <thead>
    <tr>
        <th>ID</th>
        <th>Customer</th>
        <th>Status</th>
    </tr>
    </thead>
    <tbody>
        <tr data-toggle="modal" data-id="1" data-target="#orderModal">
            <td>1</td>
            <td>24234234</td>
            <td>A</td>
        </tr>
        <tr data-toggle="modal" data-id="2" data-target="#orderModal">
            <td>2</td>
            <td>24234234</td>
            <td>A</td>
        </tr>
        <tr data-toggle="modal" data-id="3" data-target="#orderModal">
            <td>3</td>
            <td>24234234</td>
            <td>A</td>
        </tr>
    </tbody>
</table>
<div id="orderModalxx" class="modal hide fade" role="dialog" aria-labelledby="orderModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
         <h3>Order</h3>

    </div>
    <div id="orderDetails" class="modal-body"></div>
    <div id="orderItems" class="modal-body"></div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
</div>



<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>

<!-- Modal -->
<div id="orderModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4  class="modal-title">please</h4>
      </div>
      <div class="modal-body">
        <p id="orderItems"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<!--
<a href="{{ route('tasks.index') }}" class="btn btn-info">View Tasks</a>
<a href="{{ route('tasks.create') }}" class="btn btn-primary">Add New Task</a>
-->






@stop

resources/views/rosters/create.blade.php
@extends('layouts.master')

@section('content')

{!! Form::open([
    'route' => 'rosters.store'

]) !!}

<div class="form-group">

 



    {!! Form::label('title', 'Sport:', ['class' => 'control-label']) !!}
    {{ Form::select('sport_id', $sports), ['class' => 'form-control'] }}
</div>
<div class="form-group">
    {!! Form::label('title', 'Level:', ['class' => 'control-label']) !!}
     {{ Form::select('level_id', $levels), ['class' => 'form-control'] }}
<div class="form-group">
    {!! Form::label('title', 'Year:', ['class' => 'control-label']) !!}
     {{ Form::select('year_id', $years), ['class' => 'form-control'] }}
</div>

<div class="form-group">
    {!! Form::label('title', 'First Name:', ['class' => 'control-label']) !!}
    {!! Form::text('first_name', null, ['class' => 'fn']) !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'Last Name:', ['class' => 'control-label']) !!}
    {!! Form::text('last_name', null, ['class' => 'ln']) !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'Jersey:', ['class' => 'control-label']) !!}
    {!! Form::text('jersey', null, ['class' => 'jersey']) !!}
</div>

<div class="form-group">
    {!! Form::label('title', 'Position:', ['class' => 'control-label']) !!}
    {!! Form::text('position', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'Height:', ['class' => 'control-label']) !!}
    {!! Form::text('height_feet', null, ['class' => 'form-control']) !!}
    {!! Form::text('height_inches', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'Weight:', ['class' => 'control-label']) !!}
    {!! Form::text('weight', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'Hometown:', ['class' => 'control-label']) !!}
    {!! Form::text('hometown', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'Years at SFC:', ['class' => 'control-label']) !!}
    {!! Form::text('years_at_sfc', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'Verse:', ['class' => 'control-label']) !!}
    {!! Form::text('verse', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'Food:', ['class' => 'control-label']) !!}
    {!! Form::text('food', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('title', 'Photo:', ['class' => 'control-label']) !!}
    {!! Form::text('photo', null, ['class' => 'picture']) !!}
</div>


{!! Form::submit('Create Player', ['class' => 'btn btn-primary']) !!}

{!! Form::close() !!}

@stop

resources/views/rosters/index.blade.php
@extends('layouts.master')

@section('content')


<h1>Roster List</h1>
<p class="lead">Here's a list of all your players. <a href="/rosters/create">Add a new one?</a></p>
<hr>


                        <div class="panel panel-primary">
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead  style="background-color:#337AB7; color:white">
                                        <tr>  
                                            <th>  </th>
                                            <th>Jersey</th>                                      
                                            <th>Name</th>
                                            <th>Position</th>
                                            <th>Detail</th>
                                            <th>Edit</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    	@foreach($rosters as $roster)
                                        <tr>
                                        	<td><img src="{{ $roster->photo }}" alt="{ $roster->first_name }}&nbsp{{ $roster->last_name}}"  height="42"></td>
                                            <td class="ns">{{ $roster->jersey }}</td>
                                            <td>{{ $roster->first_name }}&nbsp{{ $roster->last_name}}</td>
                                            <td>{{ $roster->position}}</td>
                                            <td> <button type="button" class="use-address" data-toggle="modal" data-target="#myModal">Open Modal</button></td>
                                            <td><button type="button" class="use-address" /></td>
                                        </tr>
                                        @endforeach
                               

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>







 <table id="choose-address-table" class="ui-widget ui-widget-content">
    <thead>
        <tr class="ui-widget-header ">
            <th>Name/Nr.</th>
            <th>Street</th>
            <th>Town</th>
            <th>Postcode</th>
            <th>Country</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="nr"><span>50</span>
            </td>
            <td class="ns">Some Street 1</td>
            <td>Glasgow</td>
            <td>G0 0XX</td>
            <td>United Kingdom</td>
            <td>
                <button type="button" class="use-address" />
            </td>
        </tr>
        <tr>
            <td class="nr">49</td>
            <td class="ns">Some Street 2</td>
            <td>Glasgow</td>
            <td>G0 0XX</td>
            <td>United Kingdom</td>
            <td>
                <button type="button" class="use-address" />
            </td>
        </tr>
    </tbody>
</table>
  
<input type="text" >

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-md">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
                  <div class="row">
            <div class="col-md-6">
				        <div class="form-group-sm">
			<div class="col-s-3">
    {!! Form::label('title', 'First Name:', ['class' => 'control-label']) !!}
    {!! Form::text('first_name', null, ['class' => 'form-control', 'id'=> 'first_name']) !!}
            </div></div></div>
            <div class="col-md-6">
            <div class="form-group-sm">
			<div class="col-s-3">
    {!! Form::label('title', 'Last Name:', ['class' => 'control-label']) !!}
    {!! Form::text('last_name', null, ['class' => 'form-control']) !!}
            </div></div></div>
          </div>
                            <div class="row">
            <div class="col-md-6">
				        <div class="form-group-sm">
			<div class="col-s-3">
    {!! Form::label('title', 'Jersey:', ['class' => 'control-label']) !!}
    {!! Form::text('jersey', null, ['class' => 'form-control']) !!}
            </div></div></div>
            <div class="col-md-6">
            <div class="form-group-sm">
			<div class="col-s-3">
    {!! Form::label('title', 'Position:', ['class' => 'control-label']) !!}
    {!! Form::text('position', null, ['class' => 'form-control']) !!}
            </div></div></div>
          </div>
                            <div class="row">
            <div class="col-md-6">
				        <div class="form-group-sm">
			<div class="col-s-3">
    {!! Form::label('title', 'First Name:', ['class' => 'control-label']) !!}
    {!! Form::text('first_name', null, ['class' => 'form-control', 'id'=> 'idx']) !!}
            </div></div></div>
            <div class="col-md-6">
            <div class="form-group-sm">
			<div class="col-s-3">
    {!! Form::label('title', 'First Name:', ['class' => 'control-label']) !!}
    {!! Form::text('first_name', null, ['class' => 'form-control', 'id'=> 'idx']) !!}
            </div></div></div>
          </div>
                            <div class="row">
            <div class="col-md-6">
				        <div class="form-group-sm">
			<div class="col-s-3">
    {!! Form::label('title', 'First Name:', ['class' => 'control-label']) !!}
    {!! Form::text('first_name', null, ['class' => 'form-control', 'id'=> 'idx']) !!}
            </div></div></div>
            <div class="col-md-6">
            <div class="form-group-sm">
			<div class="col-s-3">
    {!! Form::label('title', 'First Name:', ['class' => 'control-label']) !!}
    {!! Form::text('first_name', null, ['class' => 'form-control', 'id'=> 'idx']) !!}
            </div></div></div>
          </div>
                            <div class="row">
            <div class="col-md-6">
				        <div class="form-group-sm">
			<div class="col-s-3">
    {!! Form::label('title', 'First Name:', ['class' => 'control-label']) !!}
    {!! Form::text('first_name', null, ['class' => 'form-control', 'id'=> 'idx']) !!}
            </div></div></div>
            <div class="col-md-6">
            <div class="form-group-sm">
			<div class="col-s-3">
    {!! Form::label('title', 'First Name:', ['class' => 'control-label']) !!}
    {!! Form::text('first_name', null, ['class' => 'form-control', 'id'=> 'idx']) !!}
            </div></div></div>
          </div>
                            <div class="row">
            <div class="col-md-6">
				        <div class="form-group-sm">
			<div class="col-s-3">
    {!! Form::label('title', 'First Name:', ['class' => 'control-label']) !!}
    {!! Form::text('first_name', null, ['class' => 'form-control', 'id'=> 'idx']) !!}
            </div></div></div>
            <div class="col-md-6">
            <div class="form-group-sm">
			<div class="col-s-3">
    {!! Form::label('title', 'First Name:', ['class' => 'control-label']) !!}
    {!! Form::text('first_name', null, ['class' => 'form-control', 'id'=> 'idx']) !!}
            </div></div></div>
          </div>
        
        <div class="form-group-sm">
			<div class="col-xs-3">

 



    {!! Form::label('title', 'Sport:', ['class' => 'control-label']) !!}
    {{ Form::select('sport_id', $sports), ['class' => 'form-control', 'hidden'=>'true'] }}

    {!! Form::label('title', 'Level:', ['class' => 'control-label']) !!}
     {{ Form::select('level_id', $levels), ['class' => 'form-control'] }}

    {!! Form::label('title', 'Year:', ['class' => 'control-label']) !!}
     {{ Form::select('year_id', $years), ['class' => 'form-control'] }}

    {!! Form::label('title', 'First Name:', ['class' => 'control-label']) !!}
    {!! Form::text('first_name', null, ['class' => 'form-control', 'id'=> 'idx']) !!}








    {!! Form::text('height_inches', null, ['class' => 'form-control']) !!}

    {!! Form::label('title', 'Weight:', ['class' => 'control-label']) !!}
    {!! Form::text('weight', null, ['class' => 'form-control']) !!}

    {!! Form::label('title', 'Hometown:', ['class' => 'control-label']) !!}
    {!! Form::text('hometown', null, ['class' => 'form-control']) !!}

    {!! Form::label('title', 'Years at SFC:', ['class' => 'control-label']) !!}
    {!! Form::text('years_at_sfc', null, ['class' => 'form-control']) !!}

    {!! Form::label('title', 'Verse:', ['class' => 'control-label']) !!}
    {!! Form::text('verse', null, ['class' => 'form-control']) !!}

    {!! Form::label('title', 'Food:', ['class' => 'control-label']) !!}
    {!! Form::text('food', null, ['class' => 'form-control']) !!}

    {!! Form::label('title', 'Photo:', ['class' => 'control-label']) !!}
    {!! Form::text('photo', null, ['class' => 'form-control']) !!}



{!! Form::submit('Create Player', ['class' => 'btn btn-primary']) !!}
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
{!! Form::close() !!}
</div>
</div>

        
        
        
        
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
   
  
@stop

resources/views/rosters/show.blade.php
@extends('layouts.master')

@section('content')
<img src="{{ $rosters->photo }}" alt="{{ $rosters->first_name }}&nbsp{{ $rosters->last_name}}"  height="250">
<h1>{{ camel_case($rosters->first_name) }}&nbsp{{ $rosters->last_name }}</h1>
<h1>#{{ $rosters->jersey }}</h1>

<p class="lead">{{ $rosters->level->name }}</p>
<p class="lead">{{ $rosters->year->name }}</p>
<p class="lead">{{ $rosters->position }}</p>
<p class="lead">{{ $rosters->years_at_sfc }}</p>
<p class="lead">{{ $rosters->height_feet }}'&nbsp{{ $rosters->height_inches }}"</p>
<p class="lead">{{ $rosters->weight }}Lbs.</p>
<p class="lead">{{ $rosters->hometown }}</p>
<p class="lead">{{ $rosters->verse }}</p>
<p class="lead">{{ $rosters->food }}</p>





<hr>

<div class="row">
    <div class="col-md-6">
        <a href="{{ route('rosters.index') }}" class="btn btn-info">Back to all players</a>
        <a href="{{ route('rosters.edit', $rosters->id) }}" class="btn btn-primary">Edit Player</a>
    </div>
    <div class="col-md-6 text-right">
        {!! Form::open([
            'method' => 'DELETE',
            'route' => ['rosters.destroy', $rosters->id]
        ]) !!}
            {!! Form::submit('Delete me??', ['class' => 'btn btn-danger']) !!}
        {!! Form::close() !!}
    </div>
</div>




@stop